services:
  pgadmin:
    container_name: ms_pgadmin
    image: elestio/pgadmin:REL-9_6
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 8080
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5001:8080"
    restart: unless-stopped

  brgy-database:
    container_name: brgydb
    image: postgres
    environment:
      POSTGRES_USER: brgy
      POSTGRES_PASSWORD: brgydb
      PGDATA: /var/lib/postgresql/data/brgy
    volumes:
      - brgy-data:/var/lib/postgresql/data/brgy
    ports:
      - "5439:5432"
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:26.3.3
    ports:
      - "8080:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    command:
      - "start-dev"
    volumes:
      - keycloak-data:/opt/keycloak/data

  maildev:
    container_name: maildev
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9094:9094"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    networks:
      - app-tier

volumes:
  postgres_account_data:
  postgres_residents_data:
  postgres_official_data:
  blotter-db-data:
  complaint-db-data:
  disasterAndEmergency-db-data:
  healthAndSanitation-db-data:
  incident-db-data:
  pgadmin:
  keycloak-data:
  brgy-data:

networks:
  app-tier:
    driver: bridge