spring:
  application:
    name: residents-service
  config:
    import: optional:configserver:http://localhost:8888

cloudinary_url: cloudinary://158455447741125:lMGeIpP6iuPxFgQQCZld5ELfh9U@dwwcralpu