spring:
  datasource:
    url: jdbc:postgresql://localhost:5401/account
    username: brgy
    password: accountdb
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always

server:
  port: 7001
