spring:
  datasource:
    url: jdbc:postgresql:${ACCOUNT_DATASOURCE_URL://localhost:5401}/account
    username: brgy
    password: ${ACCOUNT_DATASOURCE_PASSWORD:accountdb}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always

jwt:
  auth:
    issuerPath: ${ACCOUNT_ISSUERPATH:http://localhost:8080/realms/master}
    client-id: authId
    client-secret: ${ACCOUNT_CLIENT_SECRET:WAvJxYvKRu2efeem28DeWaQxBxFrKVz6}
    principle-attribute: preferred_username
    realm-name: master
    resident-id: resident_id
server:
  port: ${ports.account}
