spring:
  datasource:
    url: jdbc:postgresql:${DATASOURCE_URL://localhost:5439}/account

jwt:
  auth:
    issuerPath: ${ACCOUNT_ISSUERPATH:http://localhost:8080/realms/master}
    client-id: authId
    client-secret: ${ACCOUNT_CLIENT_SECRET:WAvJxYvKRu2efeem28DeWaQxBxFrKVz6}
    principle-attribute: preferred_username
    realm-name: master
    resident-id: resident_id
server:
  port: ${ports.account}
