spring:
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: ${jwt.auth.issuerPath}
#          jwk-set-uri: ${jwt.auth.issuerPath}/protocol/openid-connect/certs
  datasource:
    url: jdbc:postgresql://localhost:5401/account
    username: brgy
    password: accountdb
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always

jwt:
  auth:
    issuerPath: http://localhost:8080/realms/master
    client-id: authId
    client-secret: RMQpgavJeUlC3zVKpMfsQQ1aw5CBlV5L
    principle-attribute: preferred_username
    realm-name: master
    resident-id: resident_id
server:
  port: ${ports.account}
