spring:
  datasource:
    url: jdbc:postgresql:${BLOTTER_DATASOURCE_URL://localhost:5404/blotter}
    username: brgy
    password: blotter
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-version: 0

server:
  port: ${ports.blotter}