spring:
  datasource:
    url: jdbc:postgresql:${DATASOURCE_URL://localhost:5439}/complaint

  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-version : 0

server:
  port: ${ports.complaint}