spring:
  datasource:
    url: jdbc:postgresql:${DATASOURCE_URL://localhost:5439}/disasterAndEmergency
    username: brgy
    password: ${DATASOURCE_PASSWORD:brgydb}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always

  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-version : 0

server:
  port: ${ports.dae}