spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${jwt.auth.issuerPath}
          jwk-set-uri: ${jwt.auth.issuerPath}/protocol/openid-connect/certs
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
#          routes:
#            - id: ${routes.account}-service
#              uri: lb:http://${routes.account}-service
#              predicates:
#                - Path=${version.api}/${routes.account}/**
#            - id: ${routes.residents}-service
#              uri: lb:http://${routes.residents}-service
#              predicates:
#                - Path=${version.api}/residents/**
#            - id: officials-service
#              uri: lb:http://officials-service
#              predicates:
#                - Path=${version.api}/officials/**
#            - id: blotter-service
#              uri: lb:http://blotter-service
#              predicates:
#                - Path=${version.api}/blotter/**
server:
  port: ${ports.gateway}

jwt:
  auth:
    issuerPath: http://localhost:8080/realms/auth
    client-id: authId
    principle-attribute: preferred_username

version:
  api: /api/v1

routes:
  account: account
  residents: residents
  officials: officials
  blotter: blotter


