spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${jwt.auth.issuerPath}
          jwk-set-uri: ${jwt.auth.issuerPath}/protocol/openid-connect/certs
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          routes:
            - id: account-service
              uri: lb:http://account-service
              predicates:
                - Path=/api/v1/accounts/**
            - id: residents-service
              uri: lb:http://residents-service
              predicates:
                - Path=/api/v1/residents/**
            - id: officials-service
              uri: lb:http://officials-service
              predicates:
                - Path=/api/v1/officials/**
server:
  port: 8222

jwt:
  auth:
    issuerPath: http://localhost:8080/realms/auth
    client-id: authId
    principle-attribute: preferred_username

logging:
  level:
    org:
      springframework:
        security=DEBUG: