spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${jwt.auth.issuerPath}
          jwk-set-uri: ${jwt.auth.issuerPath}/protocol/openid-connect/certs
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false

server:
  port: ${ports.gateway}

jwt:
  auth:
    issuerPath: ${GATEWAY_ISSUERPATH:http://localhost:8080/realms/master}
    client-id: authId

version:
  api: /api/v1

routes:
  account: account
  residents: residents
  officials: officials
  blotter: blotter


