spring:
  datasource:
    url: jdbc:postgresql:${DATASOURCE_PATH://localhost:5439}/healthAndSanitation

  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-version : 0

server:
  port: ${ports.has}