spring:
  datasource:
    url: jdbc:postgresql://localhost:5407/healthAndSanitation
    username: brgy
    password: has
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-version : 0

server:
  port: ${ports.has}