spring:
  datasource:
    url: jdbc:postgresql://localhost:5408/incident
    username: brgy
    password: incident
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-version : 0

server:
  port: 7105