spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: renzvanni626@gmail.com
    password: ofec aqoz jfbh xiol
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true