spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: renzvanni626@gmail.com
    password: ${GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: ${ports.notification}