spring:
  datasource:
    url: jdbc:postgresql://localhost:5403/officials
    username: brgy
    password: officialsdb
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always

server:
  port: 7002