spring:
  datasource:
    url: jdbc:postgresql:${OFFICIALS_DATASOURCE_URL://localhost:5403/officials}
    username: brgy
    password: officialsdb
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always

server:
  port: ${ports.officials}