spring:
  datasource:
    url: jdbc:postgresql:${RESIDENTS_DATASOURCE_URL://localhost:5402/residents}
    username: brgy
    password: residentsdb
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always

server:
  port: ${ports.residents}