spring:
  datasource:
    url: jdbc:postgresql://localhost:5402/residents
    username: brgy
    password: residentsdb
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always

server:
  port: 7003