spring:
  datasource:
    url: jdbc:postgresql:${DATASOURCE_URL://localhost:5402}/residents
    username: brgy
    password: ${DATASOURCE_PASSWORD:residentsdb}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always

server:
  port: ${ports.residents}