spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        git:
          uri: file://${user.home}/config-repo
        native:
          search-locations: classpath:/configurations

server:
  port: $PORT:${CONFIG_PORT:8888}}
